const imgSlide = [
    {name: "Stranger Things", img: "https://www.wallpapertip.com/wmimgs/7-74031_wallpaper-stranger-things.jpg", logo: "https://logos-world.net/wp-content/uploads/2020/05/Stranger-Things-Logo.png", description : `Stranger Things is an American science fiction drama television series created by the Duffer
    Brothers , who also serve as showrunners and are executive producers along with Shawn Levy and
             Dan Cohen . Its first season was released on Netflix on July 15, 2016. In February 2022, the series
             was renewed for a fifth and final season.` },
    {name: "Moeny Heist", img: "https://besttoppers.com/wp-content/uploads/2020/09/money-heist-season-5.jpg", logo: "https://occ-0-1722-92.1.nflxso.net/dnm/api/v6/H8D6qtacWfxpwORI6dw3sYdASQc/AAAABTg9ihCdTCoVy2GB28LehJXNfGXw2kzOy-Gw6m021OBpUuPQ8U1o60dA6OLnNcS8kNM6hRrCLE5BjgEa-CrxXaDhxbPi1tM2LYtIJnTmQ5AD0mVtCriwVmtc8P9az7U5uLNeaVna6XHAu1Eittki4JIpdhEXomUW-jA0pezJ5vGtUQ.png?r=5d1", description : `A large part of the show revolves around Will Robinson's connection to an alien robot and an alien engine capable of interstellar travel that a small group of humans had previously and secretly stolen from the robots. An army of other robots, much like Will's robot, try to take the engine back, stranding everyone in deep space. The army is led by a robot dubbed "SAR" (Second Alien Robot). The robots' creators are largely unknown, except for the fact that they are extinct.` },
    {name: "Knives Out", img: "https://image.tmdb.org/t/p/original/ocqXvTtjvmEGcSa8Yo1Wehkyf6i.jpg", logo: "https://image.tmdb.org/t/p/original/aYKRKkxwkHTP3sGHp8E5tnNHhvy.png", description: `When renowned crime novelist Harlan Thrombey (Christopher Plummer) is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc (Daniel Craig) is mysteriously enlisted to investigate. From Harlan's disfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.` },
    {name: "DareDevil", img: "https://getwallpapers.com/wallpaper/full/1/d/4/12483.jpg", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Daredevil_Logo.svg/1280px-Daredevil_Logo.svg.png", description: "As a child Matt Murdock was blinded by a chemical spill in a freak accident. Instead of limiting him it gave him superhuman senses that enabled him to see the world in a unique and powerful way. Now he uses these powers to deliver justice, not only as a lawyer in his own law firm, but also as vigilante at night, stalking the streets of Hell's Kitchen as Daredevil, the man without fear." },
    {name : "Lock & Key", img : "https://i0.wp.com/tvshows.480mkv.com/wp-content/uploads/2020/02/Locke-Key-Posters.jpg?fit=2470%2C1082&ssl=1", logo : "https://www.viaxesports.com/wp-content/uploads/2020/01/LockeKey_TT_Final-1.png", description : `After their father is murdered under mysterious circumstances, the three Locke siblings and their mother move into their ancestral home, Keyhouse, which they discover is full of magical keys that may be connected to their father's death.After their father is murdered under mysterious circumstances, the three Locke siblings`},
    {name : "The Witcher", img : "https://wallpaperaccess.com/full/2052769.jpg", logo : `https://occ-0-3111-116.1.nflxso.net/dnm/api/v6/jsgGe9NCko3c-j0wGZ7FSwVlHs0/AAAABYF3Xjy14Ohbc1H7qoye105g2Vo_k6urJpRAyBn0DxIkGoRAinOtvnit2Wt3iF5wbVfpfzwBAOsmDuN6zL2eCFo1HoOglFaA_eUHQyeKXSoDJb-psYn7qNaqUBVGIhHXowsZvp9LDjMZDbk8iQHkI80w6D5kIYPrWN_bZDvJN8p92A.png?r=1f6`, description : `The story begins with Geralt of Rivia, Crown Princess Ciri of Cintra, and the sorceress Yennefer of Vengerberg at different points of time, exploring formative events that shape their characters throughout the first season, before eventually merging into a single timeline.
Geralt and Ciri are linked by destiny since before she was born when he unknowingly demanded her as a reward for his services by invoking "the Law of Surprise". After the two finally meet, Geralt becomes the princess's protector and must help her and fight against her various pursuers to prevent her Elder Blood and powerful magic from being used for malevolent purposes and keep Ciri and their world safe.`}
]


export default imgSlide;